### ISSUE TITLE
[feature request] add time filter argument

### ISSUE THREAD

**Issue by inkrement** [sebinsua/scrape-twitter#3]
would be great if you add a time arguments like this:
```
scrape-twitter search --query "from:afoolswisdom motivation" --from 04-02-2016 --to 05-02-2016
```

**Comment by sebinsua** [comment]
Hi.

Sorry for the long response time. It turns out I wasn't watching my own repo...?! I only found this by complete fluke. 😂

I could add this feature, but it turns out we don't need to!

```
scrape-twitter search --query="from:afoolswisdom motivation since:2016-01-01 until:2016-12-05"
```

As you can see Twitter search already supports passing in dates using `since:yyyy-mm-dd until:yyyy-mm-dd`.

I'm going to close this, but you can re-open if that doesn't suffice.

**Comment by inkrement** [comment]
thanks!
